Ext.define('PIS.view.Notification.NotificationsController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.notification-notifications',
    init:function()
    {
        this.populateNotification();
    },
    populateNotification(){
        var view=this.getView();
        var notification=[
            "Drive is late",
            "Reminders: Don't forget: This Friday is the last day to register for [classes, webinar, training, etc",
            "Support Ticket, Maintenance Request or Help Desk Status/Progress: Your ticket has been created; we'll be in touch soon!",
            "Action required or requested: From turn-based game notifications: It's your move! to conversation replies: Your contact is waiting to hear back from you push notifications are fantastic for nudging users to take in-the-moment action.",
            "Action required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation replies",
            "Action required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation replies",
            "Action required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation replies",
            "Action required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation replies",
            "Action required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation replies",
            "Action required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation replies",
            "Action required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation replies",
            "Action required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation repliesAction required or requested: From turn-based game notifications: It's your move! to conversation replies",
        ]
        notification.forEach(function(value){
            view.add({html:value,title:value})
        })        
    }

});
